/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.View;

/**
 *
 * @author macgarcia
 */
public class JPropertyCard extends javax.swing.JPanel {
    
    public String strRent [] = {"nada"};
    /**
     * Creates new form JPropertyCard
     */
    public JPropertyCard() {
        initComponents();
        //this.jList1.setListData(strRent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_0Houses = new javax.swing.JLabel();
        jLabel_1HouseRnt = new javax.swing.JLabel();
        jLabel_4HouseRnt = new javax.swing.JLabel();
        jLabel_2HouseRnt = new javax.swing.JLabel();
        jLabel_3HouseRnt = new javax.swing.JLabel();
        jLabel_Morgage = new javax.swing.JLabel();
        jLabel_HotelRnt = new javax.swing.JLabel();
        jLabel_HosesCst = new javax.swing.JLabel();
        jLabel_Information = new javax.swing.JLabel();
        jLabel_HotelsCst1 = new javax.swing.JLabel();
        jLabel_information2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(269, 317));
        setMinimumSize(new java.awt.Dimension(263, 307));
        setPreferredSize(new java.awt.Dimension(273, 305));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_Name.setBackground(new java.awt.Color(153, 153, 153));
        jLabel_Name.setFont(new java.awt.Font("Copperplate", 1, 18)); // NOI18N
        jLabel_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Name.setText("Property");
        jLabel_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_Name.setOpaque(true);

        jLabel_0Houses.setFont(new java.awt.Font("Font Shui", 0, 13)); // NOI18N
        jLabel_0Houses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_0Houses.setText("Rent $");

        jLabel_1HouseRnt.setFont(new java.awt.Font("Font Shui", 0, 12)); // NOI18N
        jLabel_1HouseRnt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_1HouseRnt.setText("Rent $");

        jLabel_4HouseRnt.setFont(new java.awt.Font("Font Shui", 0, 12)); // NOI18N
        jLabel_4HouseRnt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_4HouseRnt.setText("Rent $");

        jLabel_2HouseRnt.setFont(new java.awt.Font("Font Shui", 0, 12)); // NOI18N
        jLabel_2HouseRnt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_2HouseRnt.setText("Rent $");

        jLabel_3HouseRnt.setFont(new java.awt.Font("Font Shui", 0, 12)); // NOI18N
        jLabel_3HouseRnt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_3HouseRnt.setText("Rent $");

        jLabel_Morgage.setFont(new java.awt.Font("Font Shui", 0, 10)); // NOI18N
        jLabel_Morgage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Morgage.setText("Rent $");

        jLabel_HotelRnt.setFont(new java.awt.Font("Font Shui", 0, 13)); // NOI18N
        jLabel_HotelRnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_HotelRnt.setText("Rent $");

        jLabel_HosesCst.setFont(new java.awt.Font("Font Shui", 0, 10)); // NOI18N
        jLabel_HosesCst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_HosesCst.setText("Rent $");

        jLabel_Information.setFont(new java.awt.Font("Futura", 0, 10)); // NOI18N
        jLabel_Information.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Information.setText("If a player owns ALL the Lots of any Color-Group,  ");

        jLabel_HotelsCst1.setFont(new java.awt.Font("Font Shui", 0, 10)); // NOI18N
        jLabel_HotelsCst1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_HotelsCst1.setText("Rent $");

        jLabel_information2.setFont(new java.awt.Font("Futura", 0, 10)); // NOI18N
        jLabel_information2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_information2.setText(" the rent is Doubled on Unimproved Lots in that group.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_HotelsCst1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_information2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel_Morgage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_HosesCst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel_0Houses, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_HotelRnt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_1HouseRnt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_2HouseRnt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_3HouseRnt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_4HouseRnt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_0Houses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_1HouseRnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_2HouseRnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_3HouseRnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_4HouseRnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_HotelRnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Morgage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_HosesCst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_HotelsCst1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Information)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_information2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel_0Houses;
    public javax.swing.JLabel jLabel_1HouseRnt;
    public javax.swing.JLabel jLabel_2HouseRnt;
    public javax.swing.JLabel jLabel_3HouseRnt;
    public javax.swing.JLabel jLabel_4HouseRnt;
    public javax.swing.JLabel jLabel_HosesCst;
    public javax.swing.JLabel jLabel_HotelRnt;
    public javax.swing.JLabel jLabel_HotelsCst1;
    private javax.swing.JLabel jLabel_Information;
    public javax.swing.JLabel jLabel_Morgage;
    public javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_information2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
