/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.View;

/**
 *
 * @author macgarcia
 */
public class TradeDisplay extends javax.swing.JFrame {

    /**
     * Creates new form TradeDisplay
     */
    public TradeDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jPropertyCard_Player = new Client.View.JPropertyCard();
        jTextField_MoneyPlayer = new javax.swing.JTextField();
        jTextField_MoneyEnemy = new javax.swing.JTextField();
        jButton_DeletePlayer = new javax.swing.JButton();
        jButton_AddPlayer = new javax.swing.JButton();
        jButton_AddEnemy = new javax.swing.JButton();
        jButton_DeleteEnemy = new javax.swing.JButton();
        jButton_LeftPropertyPlayer = new javax.swing.JButton();
        jButton_RightPropertyPlayer = new javax.swing.JButton();
        jButton_Confirm = new javax.swing.JButton();
        jTabbedPane_Information7 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jLayeredPane23 = new javax.swing.JLayeredPane();
        jUtilityCard5 = new Client.View.JChanceCard();
        jLayeredPane24 = new javax.swing.JLayeredPane();
        jStationCard5 = new Client.View.JStationCard();
        jButton_LeftStationEnemy1 = new javax.swing.JButton();
        jButton_StationEnemy1 = new javax.swing.JButton();
        jLayeredPane25 = new javax.swing.JLayeredPane();
        jCommunityCard5 = new Client.View.JCommunityCard();
        jLayeredPane26 = new javax.swing.JLayeredPane();
        jUtility5 = new Client.View.JUtilityCard();
        jButton_LeftUtilityEnemy1 = new javax.swing.JButton();
        jButton_RightUtilityEnemy1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_money1 = new javax.swing.JLabel();
        jLayeredPane22 = new javax.swing.JLayeredPane();
        jPropertyCard6 = new Client.View.JPropertyCard();
        jButton_RightPropertyEnemy1 = new javax.swing.JButton();
        jButton_LeftPropertyEnemy1 = new javax.swing.JButton();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jLayeredPane27 = new javax.swing.JLayeredPane();
        jPropertyCard7 = new Client.View.JPropertyCard();
        jButton_RightPropertyEnemy2 = new javax.swing.JButton();
        jButton_LeftPropertyEnemy2 = new javax.swing.JButton();
        jLayeredPane28 = new javax.swing.JLayeredPane();
        jUtilityCard6 = new Client.View.JChanceCard();
        jLayeredPane29 = new javax.swing.JLayeredPane();
        jStationCard6 = new Client.View.JStationCard();
        jButton_LeftStationEnemy2 = new javax.swing.JButton();
        jButton_StationEnemy2 = new javax.swing.JButton();
        jLayeredPane30 = new javax.swing.JLayeredPane();
        jCommunityCard6 = new Client.View.JCommunityCard();
        jLayeredPane31 = new javax.swing.JLayeredPane();
        jUtility6 = new Client.View.JUtilityCard();
        jButton_LeftUtilityEnemy2 = new javax.swing.JButton();
        jButton_RightUtilityEnemy2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_money2 = new javax.swing.JLabel();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jLayeredPane32 = new javax.swing.JLayeredPane();
        jPropertyCard8 = new Client.View.JPropertyCard();
        jButton_RightPropertyEnemy3 = new javax.swing.JButton();
        jButton_LeftPropertyEnemy3 = new javax.swing.JButton();
        jLayeredPane33 = new javax.swing.JLayeredPane();
        jUtilityCard7 = new Client.View.JChanceCard();
        jLayeredPane34 = new javax.swing.JLayeredPane();
        jStationCard7 = new Client.View.JStationCard();
        jButton_LeftStationEnemy3 = new javax.swing.JButton();
        jButton_RightStationEnemy3 = new javax.swing.JButton();
        jLayeredPane35 = new javax.swing.JLayeredPane();
        jCommunityCard7 = new Client.View.JCommunityCard();
        jLayeredPane36 = new javax.swing.JLayeredPane();
        jUtility7 = new Client.View.JUtilityCard();
        jButton_LeftUtilityEnemy3 = new javax.swing.JButton();
        jButton_RightUtilityEnemy3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_money3 = new javax.swing.JLabel();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jLayeredPane37 = new javax.swing.JLayeredPane();
        jPropertyCard9 = new Client.View.JPropertyCard();
        jButton_RightPropertyEnemy4 = new javax.swing.JButton();
        jButton_LeftPropertyEnemy4 = new javax.swing.JButton();
        jLayeredPane38 = new javax.swing.JLayeredPane();
        jUtilityCard8 = new Client.View.JChanceCard();
        jLayeredPane39 = new javax.swing.JLayeredPane();
        jStationCard8 = new Client.View.JStationCard();
        jButton_LeftStationEnemy4 = new javax.swing.JButton();
        jButton_StationEnemy4 = new javax.swing.JButton();
        jLayeredPane40 = new javax.swing.JLayeredPane();
        jCommunityCard8 = new Client.View.JCommunityCard();
        jLayeredPane41 = new javax.swing.JLayeredPane();
        jUtility8 = new Client.View.JUtilityCard();
        jButton_LeftUtilityEnemy4 = new javax.swing.JButton();
        jButton_RightUtilityEnemy4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_money4 = new javax.swing.JLabel();
        jButton_LeftUtilityEnemy5 = new javax.swing.JTabbedPane();
        jLayeredPane42 = new javax.swing.JLayeredPane();
        jPropertyCard10 = new Client.View.JPropertyCard();
        jButton_RightPropertyEnemy5 = new javax.swing.JButton();
        jButton_LeftPropertyEnemy5 = new javax.swing.JButton();
        jLayeredPane43 = new javax.swing.JLayeredPane();
        jUtilityCard9 = new Client.View.JChanceCard();
        jLayeredPane44 = new javax.swing.JLayeredPane();
        jStationCard9 = new Client.View.JStationCard();
        jButton_LeftStationEnemy5 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jLayeredPane45 = new javax.swing.JLayeredPane();
        jCommunityCard9 = new Client.View.JCommunityCard();
        jLayeredPane46 = new javax.swing.JLayeredPane();
        jUtility9 = new Client.View.JUtilityCard();
        jButton_LeftUtility55 = new javax.swing.JButton();
        jButton_RightUtilityEnemy5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_money5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(0, 102, 102));
        jLayeredPane1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TRADE");

        jButton_DeletePlayer.setText("Delete");

        jButton_AddPlayer.setText("Add");

        jButton_AddEnemy.setText("Add");

        jButton_DeleteEnemy.setText("Delete");

        jButton_LeftPropertyPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftPropertyPlayer.setBorderPainted(false);

        jButton_RightPropertyPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightPropertyPlayer.setBorderPainted(false);

        jButton_Confirm.setText("Confirm");

        jLayeredPane23.setLayer(jUtilityCard5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane23Layout = new javax.swing.GroupLayout(jLayeredPane23);
        jLayeredPane23.setLayout(jLayeredPane23Layout);
        jLayeredPane23Layout.setHorizontalGroup(
            jLayeredPane23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane23Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jUtilityCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jLayeredPane23Layout.setVerticalGroup(
            jLayeredPane23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane23Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jUtilityCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Chance", jLayeredPane23);

        jButton_LeftStationEnemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftStationEnemy1.setBorderPainted(false);

        jButton_StationEnemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_StationEnemy1.setBorderPainted(false);

        jLayeredPane24.setLayer(jStationCard5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane24.setLayer(jButton_LeftStationEnemy1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane24.setLayer(jButton_StationEnemy1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane24Layout = new javax.swing.GroupLayout(jLayeredPane24);
        jLayeredPane24.setLayout(jLayeredPane24Layout);
        jLayeredPane24Layout.setHorizontalGroup(
            jLayeredPane24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftStationEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jStationCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_StationEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jLayeredPane24Layout.setVerticalGroup(
            jLayeredPane24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane24Layout.createSequentialGroup()
                .addGroup(jLayeredPane24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane24Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jStationCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane24Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton_StationEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane24Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftStationEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Station", jLayeredPane24);

        jLayeredPane25.setLayer(jCommunityCard5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane25Layout = new javax.swing.GroupLayout(jLayeredPane25);
        jLayeredPane25.setLayout(jLayeredPane25Layout);
        jLayeredPane25Layout.setHorizontalGroup(
            jLayeredPane25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane25Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jCommunityCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jLayeredPane25Layout.setVerticalGroup(
            jLayeredPane25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane25Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCommunityCard5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Community", jLayeredPane25);

        jButton_LeftUtilityEnemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftUtilityEnemy1.setBorderPainted(false);

        jButton_RightUtilityEnemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightUtilityEnemy1.setBorderPainted(false);

        jLayeredPane26.setLayer(jUtility5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane26.setLayer(jButton_LeftUtilityEnemy1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane26.setLayer(jButton_RightUtilityEnemy1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane26Layout = new javax.swing.GroupLayout(jLayeredPane26);
        jLayeredPane26.setLayout(jLayeredPane26Layout);
        jLayeredPane26Layout.setHorizontalGroup(
            jLayeredPane26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane26Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftUtilityEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUtility5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_RightUtilityEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jLayeredPane26Layout.setVerticalGroup(
            jLayeredPane26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane26Layout.createSequentialGroup()
                .addGroup(jLayeredPane26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane26Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUtility5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane26Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftUtilityEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane26Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton_RightUtilityEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Utility", jLayeredPane26);

        jPanel3.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/money.png"))); // NOI18N

        jLabel_money1.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        jLabel_money1.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel_money1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel_money1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Status", jPanel3);

        jButton_RightPropertyEnemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightPropertyEnemy1.setBorderPainted(false);

        jButton_LeftPropertyEnemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftPropertyEnemy1.setBorderPainted(false);

        jLayeredPane22.setLayer(jPropertyCard6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane22.setLayer(jButton_RightPropertyEnemy1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane22.setLayer(jButton_LeftPropertyEnemy1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane22Layout = new javax.swing.GroupLayout(jLayeredPane22);
        jLayeredPane22.setLayout(jLayeredPane22Layout);
        jLayeredPane22Layout.setHorizontalGroup(
            jLayeredPane22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane22Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jButton_LeftPropertyEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPropertyCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_RightPropertyEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jLayeredPane22Layout.setVerticalGroup(
            jLayeredPane22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane22Layout.createSequentialGroup()
                .addGroup(jLayeredPane22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane22Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPropertyCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane22Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton_RightPropertyEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane22Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton_LeftPropertyEnemy1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Property", jLayeredPane22);

        jTabbedPane_Information7.addTab("Enemy1", jTabbedPane8);

        jButton_RightPropertyEnemy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightPropertyEnemy2.setBorderPainted(false);

        jButton_LeftPropertyEnemy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftPropertyEnemy2.setBorderPainted(false);

        jLayeredPane27.setLayer(jPropertyCard7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane27.setLayer(jButton_RightPropertyEnemy2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane27.setLayer(jButton_LeftPropertyEnemy2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane27Layout = new javax.swing.GroupLayout(jLayeredPane27);
        jLayeredPane27.setLayout(jLayeredPane27Layout);
        jLayeredPane27Layout.setHorizontalGroup(
            jLayeredPane27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane27Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jButton_LeftPropertyEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPropertyCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_RightPropertyEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jLayeredPane27Layout.setVerticalGroup(
            jLayeredPane27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane27Layout.createSequentialGroup()
                .addGroup(jLayeredPane27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane27Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPropertyCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane27Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton_RightPropertyEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane27Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton_LeftPropertyEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("Property", jLayeredPane27);

        jLayeredPane28.setLayer(jUtilityCard6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane28Layout = new javax.swing.GroupLayout(jLayeredPane28);
        jLayeredPane28.setLayout(jLayeredPane28Layout);
        jLayeredPane28Layout.setHorizontalGroup(
            jLayeredPane28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane28Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jUtilityCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jLayeredPane28Layout.setVerticalGroup(
            jLayeredPane28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane28Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jUtilityCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("Chance", jLayeredPane28);

        jButton_LeftStationEnemy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftStationEnemy2.setBorderPainted(false);

        jButton_StationEnemy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_StationEnemy2.setBorderPainted(false);

        jLayeredPane29.setLayer(jStationCard6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane29.setLayer(jButton_LeftStationEnemy2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane29.setLayer(jButton_StationEnemy2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane29Layout = new javax.swing.GroupLayout(jLayeredPane29);
        jLayeredPane29.setLayout(jLayeredPane29Layout);
        jLayeredPane29Layout.setHorizontalGroup(
            jLayeredPane29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane29Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftStationEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jStationCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_StationEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jLayeredPane29Layout.setVerticalGroup(
            jLayeredPane29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane29Layout.createSequentialGroup()
                .addGroup(jLayeredPane29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane29Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jStationCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane29Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton_StationEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane29Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftStationEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("Station", jLayeredPane29);

        jLayeredPane30.setLayer(jCommunityCard6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane30Layout = new javax.swing.GroupLayout(jLayeredPane30);
        jLayeredPane30.setLayout(jLayeredPane30Layout);
        jLayeredPane30Layout.setHorizontalGroup(
            jLayeredPane30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane30Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jCommunityCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jLayeredPane30Layout.setVerticalGroup(
            jLayeredPane30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane30Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCommunityCard6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("Community", jLayeredPane30);

        jButton_LeftUtilityEnemy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftUtilityEnemy2.setBorderPainted(false);

        jButton_RightUtilityEnemy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightUtilityEnemy2.setBorderPainted(false);

        jLayeredPane31.setLayer(jUtility6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane31.setLayer(jButton_LeftUtilityEnemy2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane31.setLayer(jButton_RightUtilityEnemy2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane31Layout = new javax.swing.GroupLayout(jLayeredPane31);
        jLayeredPane31.setLayout(jLayeredPane31Layout);
        jLayeredPane31Layout.setHorizontalGroup(
            jLayeredPane31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftUtilityEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUtility6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_RightUtilityEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jLayeredPane31Layout.setVerticalGroup(
            jLayeredPane31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane31Layout.createSequentialGroup()
                .addGroup(jLayeredPane31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane31Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUtility6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane31Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftUtilityEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane31Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton_RightUtilityEnemy2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("Utility", jLayeredPane31);

        jPanel4.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/money.png"))); // NOI18N

        jLabel_money2.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        jLabel_money2.setText("jLabel2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel_money2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel_money2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("Status", jPanel4);

        jTabbedPane_Information7.addTab("Enemy2", jTabbedPane9);

        jButton_RightPropertyEnemy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightPropertyEnemy3.setBorderPainted(false);

        jButton_LeftPropertyEnemy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftPropertyEnemy3.setBorderPainted(false);

        jLayeredPane32.setLayer(jPropertyCard8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane32.setLayer(jButton_RightPropertyEnemy3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane32.setLayer(jButton_LeftPropertyEnemy3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane32Layout = new javax.swing.GroupLayout(jLayeredPane32);
        jLayeredPane32.setLayout(jLayeredPane32Layout);
        jLayeredPane32Layout.setHorizontalGroup(
            jLayeredPane32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane32Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jButton_LeftPropertyEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPropertyCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_RightPropertyEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jLayeredPane32Layout.setVerticalGroup(
            jLayeredPane32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane32Layout.createSequentialGroup()
                .addGroup(jLayeredPane32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane32Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPropertyCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane32Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton_LeftPropertyEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane32Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton_RightPropertyEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane10.addTab("Property", jLayeredPane32);

        jLayeredPane33.setLayer(jUtilityCard7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane33Layout = new javax.swing.GroupLayout(jLayeredPane33);
        jLayeredPane33.setLayout(jLayeredPane33Layout);
        jLayeredPane33Layout.setHorizontalGroup(
            jLayeredPane33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane33Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jUtilityCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jLayeredPane33Layout.setVerticalGroup(
            jLayeredPane33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane33Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jUtilityCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane10.addTab("Chance", jLayeredPane33);

        jButton_LeftStationEnemy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftStationEnemy3.setBorderPainted(false);

        jButton_RightStationEnemy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightStationEnemy3.setBorderPainted(false);

        jLayeredPane34.setLayer(jStationCard7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane34.setLayer(jButton_LeftStationEnemy3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane34.setLayer(jButton_RightStationEnemy3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane34Layout = new javax.swing.GroupLayout(jLayeredPane34);
        jLayeredPane34.setLayout(jLayeredPane34Layout);
        jLayeredPane34Layout.setHorizontalGroup(
            jLayeredPane34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane34Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftStationEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jStationCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_RightStationEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jLayeredPane34Layout.setVerticalGroup(
            jLayeredPane34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane34Layout.createSequentialGroup()
                .addGroup(jLayeredPane34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane34Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jStationCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane34Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton_RightStationEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane34Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftStationEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane10.addTab("Station", jLayeredPane34);

        jLayeredPane35.setLayer(jCommunityCard7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane35Layout = new javax.swing.GroupLayout(jLayeredPane35);
        jLayeredPane35.setLayout(jLayeredPane35Layout);
        jLayeredPane35Layout.setHorizontalGroup(
            jLayeredPane35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane35Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jCommunityCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jLayeredPane35Layout.setVerticalGroup(
            jLayeredPane35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane35Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCommunityCard7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane10.addTab("Community", jLayeredPane35);

        jButton_LeftUtilityEnemy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftUtilityEnemy3.setBorderPainted(false);

        jButton_RightUtilityEnemy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightUtilityEnemy3.setBorderPainted(false);

        jLayeredPane36.setLayer(jUtility7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane36.setLayer(jButton_LeftUtilityEnemy3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane36.setLayer(jButton_RightUtilityEnemy3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane36Layout = new javax.swing.GroupLayout(jLayeredPane36);
        jLayeredPane36.setLayout(jLayeredPane36Layout);
        jLayeredPane36Layout.setHorizontalGroup(
            jLayeredPane36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane36Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftUtilityEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUtility7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_RightUtilityEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jLayeredPane36Layout.setVerticalGroup(
            jLayeredPane36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane36Layout.createSequentialGroup()
                .addGroup(jLayeredPane36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane36Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUtility7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane36Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftUtilityEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane36Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton_RightUtilityEnemy3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane10.addTab("Utility", jLayeredPane36);

        jPanel5.setOpaque(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/money.png"))); // NOI18N

        jLabel_money3.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        jLabel_money3.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel_money3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel_money3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane10.addTab("Status", jPanel5);

        jTabbedPane_Information7.addTab("Enemy3", jTabbedPane10);

        jButton_RightPropertyEnemy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightPropertyEnemy4.setBorderPainted(false);

        jButton_LeftPropertyEnemy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftPropertyEnemy4.setBorderPainted(false);

        jLayeredPane37.setLayer(jPropertyCard9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane37.setLayer(jButton_RightPropertyEnemy4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane37.setLayer(jButton_LeftPropertyEnemy4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane37Layout = new javax.swing.GroupLayout(jLayeredPane37);
        jLayeredPane37.setLayout(jLayeredPane37Layout);
        jLayeredPane37Layout.setHorizontalGroup(
            jLayeredPane37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane37Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jButton_LeftPropertyEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPropertyCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_RightPropertyEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jLayeredPane37Layout.setVerticalGroup(
            jLayeredPane37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane37Layout.createSequentialGroup()
                .addGroup(jLayeredPane37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane37Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPropertyCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane37Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton_RightPropertyEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane37Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton_LeftPropertyEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane11.addTab("Property", jLayeredPane37);

        jLayeredPane38.setLayer(jUtilityCard8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane38Layout = new javax.swing.GroupLayout(jLayeredPane38);
        jLayeredPane38.setLayout(jLayeredPane38Layout);
        jLayeredPane38Layout.setHorizontalGroup(
            jLayeredPane38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane38Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jUtilityCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jLayeredPane38Layout.setVerticalGroup(
            jLayeredPane38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane38Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jUtilityCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane11.addTab("Chance", jLayeredPane38);

        jButton_LeftStationEnemy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftStationEnemy4.setBorderPainted(false);

        jButton_StationEnemy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_StationEnemy4.setBorderPainted(false);

        jLayeredPane39.setLayer(jStationCard8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane39.setLayer(jButton_LeftStationEnemy4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane39.setLayer(jButton_StationEnemy4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane39Layout = new javax.swing.GroupLayout(jLayeredPane39);
        jLayeredPane39.setLayout(jLayeredPane39Layout);
        jLayeredPane39Layout.setHorizontalGroup(
            jLayeredPane39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane39Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftStationEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jStationCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_StationEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jLayeredPane39Layout.setVerticalGroup(
            jLayeredPane39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane39Layout.createSequentialGroup()
                .addGroup(jLayeredPane39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane39Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jStationCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane39Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton_StationEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane39Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftStationEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane11.addTab("Station", jLayeredPane39);

        jLayeredPane40.setLayer(jCommunityCard8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane40Layout = new javax.swing.GroupLayout(jLayeredPane40);
        jLayeredPane40.setLayout(jLayeredPane40Layout);
        jLayeredPane40Layout.setHorizontalGroup(
            jLayeredPane40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane40Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jCommunityCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jLayeredPane40Layout.setVerticalGroup(
            jLayeredPane40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane40Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCommunityCard8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane11.addTab("Community", jLayeredPane40);

        jButton_LeftUtilityEnemy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftUtilityEnemy4.setBorderPainted(false);

        jButton_RightUtilityEnemy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightUtilityEnemy4.setBorderPainted(false);

        jLayeredPane41.setLayer(jUtility8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane41.setLayer(jButton_LeftUtilityEnemy4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane41.setLayer(jButton_RightUtilityEnemy4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane41Layout = new javax.swing.GroupLayout(jLayeredPane41);
        jLayeredPane41.setLayout(jLayeredPane41Layout);
        jLayeredPane41Layout.setHorizontalGroup(
            jLayeredPane41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane41Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftUtilityEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUtility8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_RightUtilityEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jLayeredPane41Layout.setVerticalGroup(
            jLayeredPane41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane41Layout.createSequentialGroup()
                .addGroup(jLayeredPane41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane41Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUtility8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane41Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftUtilityEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane41Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton_RightUtilityEnemy4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane11.addTab("Utility", jLayeredPane41);

        jPanel6.setOpaque(false);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/money.png"))); // NOI18N

        jLabel_money4.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        jLabel_money4.setText("jLabel2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel_money4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel_money4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane11.addTab("Status", jPanel6);

        jTabbedPane_Information7.addTab("Enemy4", jTabbedPane11);

        jButton_RightPropertyEnemy5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightPropertyEnemy5.setBorderPainted(false);

        jButton_LeftPropertyEnemy5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftPropertyEnemy5.setBorderPainted(false);

        jLayeredPane42.setLayer(jPropertyCard10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane42.setLayer(jButton_RightPropertyEnemy5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane42.setLayer(jButton_LeftPropertyEnemy5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane42Layout = new javax.swing.GroupLayout(jLayeredPane42);
        jLayeredPane42.setLayout(jLayeredPane42Layout);
        jLayeredPane42Layout.setHorizontalGroup(
            jLayeredPane42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane42Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jButton_LeftPropertyEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPropertyCard10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_RightPropertyEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jLayeredPane42Layout.setVerticalGroup(
            jLayeredPane42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane42Layout.createSequentialGroup()
                .addGroup(jLayeredPane42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane42Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPropertyCard10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane42Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton_RightPropertyEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane42Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton_LeftPropertyEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jButton_LeftUtilityEnemy5.addTab("Property", jLayeredPane42);

        jLayeredPane43.setLayer(jUtilityCard9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane43Layout = new javax.swing.GroupLayout(jLayeredPane43);
        jLayeredPane43.setLayout(jLayeredPane43Layout);
        jLayeredPane43Layout.setHorizontalGroup(
            jLayeredPane43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane43Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jUtilityCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jLayeredPane43Layout.setVerticalGroup(
            jLayeredPane43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane43Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jUtilityCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jButton_LeftUtilityEnemy5.addTab("Chance", jLayeredPane43);

        jButton_LeftStationEnemy5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftStationEnemy5.setBorderPainted(false);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton34.setBorderPainted(false);

        jLayeredPane44.setLayer(jStationCard9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane44.setLayer(jButton_LeftStationEnemy5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane44.setLayer(jButton34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane44Layout = new javax.swing.GroupLayout(jLayeredPane44);
        jLayeredPane44.setLayout(jLayeredPane44Layout);
        jLayeredPane44Layout.setHorizontalGroup(
            jLayeredPane44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane44Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftStationEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jStationCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jLayeredPane44Layout.setVerticalGroup(
            jLayeredPane44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane44Layout.createSequentialGroup()
                .addGroup(jLayeredPane44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane44Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jStationCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane44Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane44Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftStationEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_LeftUtilityEnemy5.addTab("Station", jLayeredPane44);

        jLayeredPane45.setLayer(jCommunityCard9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane45Layout = new javax.swing.GroupLayout(jLayeredPane45);
        jLayeredPane45.setLayout(jLayeredPane45Layout);
        jLayeredPane45Layout.setHorizontalGroup(
            jLayeredPane45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane45Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jCommunityCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jLayeredPane45Layout.setVerticalGroup(
            jLayeredPane45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane45Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCommunityCard9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jButton_LeftUtilityEnemy5.addTab("Community", jLayeredPane45);

        jButton_LeftUtility55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/left.png"))); // NOI18N
        jButton_LeftUtility55.setBorderPainted(false);

        jButton_RightUtilityEnemy5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/right.png"))); // NOI18N
        jButton_RightUtilityEnemy5.setBorderPainted(false);

        jLayeredPane46.setLayer(jUtility9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane46.setLayer(jButton_LeftUtility55, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane46.setLayer(jButton_RightUtilityEnemy5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane46Layout = new javax.swing.GroupLayout(jLayeredPane46);
        jLayeredPane46.setLayout(jLayeredPane46Layout);
        jLayeredPane46Layout.setHorizontalGroup(
            jLayeredPane46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane46Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_LeftUtility55, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUtility9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_RightUtilityEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jLayeredPane46Layout.setVerticalGroup(
            jLayeredPane46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane46Layout.createSequentialGroup()
                .addGroup(jLayeredPane46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane46Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUtility9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane46Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton_LeftUtility55, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane46Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton_RightUtilityEnemy5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_LeftUtilityEnemy5.addTab("Utility", jLayeredPane46);

        jPanel7.setOpaque(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/View/IconImages/money.png"))); // NOI18N

        jLabel_money5.setFont(new java.awt.Font("Phosphate", 0, 18)); // NOI18N
        jLabel_money5.setText("jLabel2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel_money5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel_money5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jButton_LeftUtilityEnemy5.addTab("Status", jPanel7);

        jTabbedPane_Information7.addTab("Enemy5", jButton_LeftUtilityEnemy5);

        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPropertyCard_Player, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_MoneyPlayer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField_MoneyEnemy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_DeletePlayer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_AddPlayer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_AddEnemy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_DeleteEnemy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_LeftPropertyPlayer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_RightPropertyPlayer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton_Confirm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTabbedPane_Information7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton_LeftPropertyPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPropertyCard_Player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_RightPropertyPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane_Information7, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jButton_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton_DeletePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_MoneyPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(jButton_AddEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_DeleteEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_MoneyEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jPropertyCard_Player, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jButton_RightPropertyPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)))
                        .addComponent(jTextField_MoneyPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane_Information7, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jButton_LeftPropertyPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_MoneyEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_DeleteEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_AddEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_DeletePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_AddPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton34;
    public javax.swing.JButton jButton_AddEnemy;
    public javax.swing.JButton jButton_AddPlayer;
    public javax.swing.JButton jButton_Confirm;
    public javax.swing.JButton jButton_DeleteEnemy;
    public javax.swing.JButton jButton_DeletePlayer;
    public javax.swing.JButton jButton_LeftPropertyEnemy1;
    public javax.swing.JButton jButton_LeftPropertyEnemy2;
    public javax.swing.JButton jButton_LeftPropertyEnemy3;
    public javax.swing.JButton jButton_LeftPropertyEnemy4;
    public javax.swing.JButton jButton_LeftPropertyEnemy5;
    public javax.swing.JButton jButton_LeftPropertyPlayer;
    public javax.swing.JButton jButton_LeftStationEnemy1;
    public javax.swing.JButton jButton_LeftStationEnemy2;
    public javax.swing.JButton jButton_LeftStationEnemy3;
    public javax.swing.JButton jButton_LeftStationEnemy4;
    public javax.swing.JButton jButton_LeftStationEnemy5;
    public javax.swing.JButton jButton_LeftUtility55;
    public javax.swing.JButton jButton_LeftUtilityEnemy1;
    public javax.swing.JButton jButton_LeftUtilityEnemy2;
    public javax.swing.JButton jButton_LeftUtilityEnemy3;
    public javax.swing.JButton jButton_LeftUtilityEnemy4;
    private javax.swing.JTabbedPane jButton_LeftUtilityEnemy5;
    public javax.swing.JButton jButton_RightPropertyEnemy1;
    public javax.swing.JButton jButton_RightPropertyEnemy2;
    public javax.swing.JButton jButton_RightPropertyEnemy3;
    public javax.swing.JButton jButton_RightPropertyEnemy4;
    public javax.swing.JButton jButton_RightPropertyEnemy5;
    public javax.swing.JButton jButton_RightPropertyPlayer;
    public javax.swing.JButton jButton_RightStationEnemy3;
    public javax.swing.JButton jButton_RightUtilityEnemy1;
    public javax.swing.JButton jButton_RightUtilityEnemy2;
    public javax.swing.JButton jButton_RightUtilityEnemy3;
    public javax.swing.JButton jButton_RightUtilityEnemy4;
    public javax.swing.JButton jButton_RightUtilityEnemy5;
    public javax.swing.JButton jButton_StationEnemy1;
    public javax.swing.JButton jButton_StationEnemy2;
    public javax.swing.JButton jButton_StationEnemy4;
    private Client.View.JCommunityCard jCommunityCard5;
    private Client.View.JCommunityCard jCommunityCard6;
    private Client.View.JCommunityCard jCommunityCard7;
    private Client.View.JCommunityCard jCommunityCard8;
    private Client.View.JCommunityCard jCommunityCard9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel_money1;
    public javax.swing.JLabel jLabel_money2;
    public javax.swing.JLabel jLabel_money3;
    public javax.swing.JLabel jLabel_money4;
    public javax.swing.JLabel jLabel_money5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane22;
    private javax.swing.JLayeredPane jLayeredPane23;
    private javax.swing.JLayeredPane jLayeredPane24;
    private javax.swing.JLayeredPane jLayeredPane25;
    private javax.swing.JLayeredPane jLayeredPane26;
    private javax.swing.JLayeredPane jLayeredPane27;
    private javax.swing.JLayeredPane jLayeredPane28;
    private javax.swing.JLayeredPane jLayeredPane29;
    private javax.swing.JLayeredPane jLayeredPane30;
    private javax.swing.JLayeredPane jLayeredPane31;
    private javax.swing.JLayeredPane jLayeredPane32;
    private javax.swing.JLayeredPane jLayeredPane33;
    private javax.swing.JLayeredPane jLayeredPane34;
    private javax.swing.JLayeredPane jLayeredPane35;
    private javax.swing.JLayeredPane jLayeredPane36;
    private javax.swing.JLayeredPane jLayeredPane37;
    private javax.swing.JLayeredPane jLayeredPane38;
    private javax.swing.JLayeredPane jLayeredPane39;
    private javax.swing.JLayeredPane jLayeredPane40;
    private javax.swing.JLayeredPane jLayeredPane41;
    private javax.swing.JLayeredPane jLayeredPane42;
    private javax.swing.JLayeredPane jLayeredPane43;
    private javax.swing.JLayeredPane jLayeredPane44;
    private javax.swing.JLayeredPane jLayeredPane45;
    private javax.swing.JLayeredPane jLayeredPane46;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public Client.View.JPropertyCard jPropertyCard10;
    public Client.View.JPropertyCard jPropertyCard6;
    public Client.View.JPropertyCard jPropertyCard7;
    public Client.View.JPropertyCard jPropertyCard8;
    public Client.View.JPropertyCard jPropertyCard9;
    public Client.View.JPropertyCard jPropertyCard_Player;
    public Client.View.JStationCard jStationCard5;
    public Client.View.JStationCard jStationCard6;
    public Client.View.JStationCard jStationCard7;
    public Client.View.JStationCard jStationCard8;
    public Client.View.JStationCard jStationCard9;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    public javax.swing.JTabbedPane jTabbedPane_Information7;
    public javax.swing.JTextField jTextField_MoneyEnemy;
    public javax.swing.JTextField jTextField_MoneyPlayer;
    public Client.View.JUtilityCard jUtility5;
    public Client.View.JUtilityCard jUtility6;
    public Client.View.JUtilityCard jUtility7;
    public Client.View.JUtilityCard jUtility8;
    public Client.View.JUtilityCard jUtility9;
    private Client.View.JChanceCard jUtilityCard5;
    private Client.View.JChanceCard jUtilityCard6;
    private Client.View.JChanceCard jUtilityCard7;
    private Client.View.JChanceCard jUtilityCard8;
    private Client.View.JChanceCard jUtilityCard9;
    // End of variables declaration//GEN-END:variables
}
